In [20]:
import numpy  as np
import pandas as pd

# Pandas is a library to handle datasets that can be organized as observations by features
# Data that you would put into a 2 dimensional schema, also higher dimensions can be used

# Create random data

var1 = np.random.randn(100) *5 +20
var2 = np.random.randn(100) > 0


# Variable labels

labels = ["Temp (C)", "Ice cream"]

# Put data together into a dictionary

D = {labels[0]: var1, labels[1]: var2}


# Import the dictionary into a pandas data frame

df = pd.DataFrame(data=D)

In [21]:
df.head()

    Temp (C)  Ice cream
0  22.256587       True
1  17.469974      False
2  19.592428      False
3  21.320063      False
4  18.668295       True

In [22]:
df.count()

Temp (C)     100
Ice cream    100
dtype: int64

In [23]:
df.mean()

Temp (C)     19.767088
Ice cream     0.390000
dtype: float64

In [29]:
# Create data set

nums = np.array(range(11))

df = pd.DataFrame({"nums":nums,"square":nums**2, "log": np.log(nums)})

# Warning
# /var/folders/mn/cj1b2_vj04n9sx9831x63z4h0000gn/T/ipykernel_46102/3525250728.py:5: RuntimeWarning: divide by zero encountered in log df = pd.DataFrame({"nums":nums,"square":nums**2, "log": np.log(nums)})

df

/var/folders/mn/cj1b2_vj04n9sx9831x63z4h0000gn/T/ipykernel_46102/3450601095.py:5: RuntimeWarning: divide by zero encountered in log
  df = pd.DataFrame({"nums":nums,"square":nums**2, "log": np.log(nums)})

    nums  square       log
0      0       0      -inf
1      1       1  0.000000
2      2       4  0.693147
3      3       9  1.098612
4      4      16  1.386294
5      5      25  1.609438
6      6      36  1.791759
7      7      49  1.945910
8      8      64  2.079442
9      9      81  2.197225
10    10     100  2.302585